### ISSUE TITLE
Support local files

### ISSUE THREAD

**Issue by bendavis78** [cbkelley/swaggerValidator#6]
When trying to validate a local swagger file, I get this:

```
/usr/lib/node_modules/swagger-validator/lib/linterHandler.js:11
        var specVersion = swaggerRootDoc.swaggerVersion || swaggerRootDoc.swagger;
                                        ^

TypeError: Cannot read property 'swaggerVersion' of undefined
    at module.exports (/usr/lib/node_modules/swagger-validator/lib/linterHandler.js:11:34)
    at /usr/lib/node_modules/swagger-validator/index.js:21:4
    at Request._callback (/usr/lib/node_modules/swagger-validator/lib/apiDefCrawler.js:26:12)
    at self.callback (/usr/lib/node_modules/swagger-validator/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.init (/usr/lib/node_modules/swagger-validator/node_modules/request/request.js:286:17)
    at new Request (/usr/lib/node_modules/swagger-validator/node_modules/request/request.js:140:8)
    at request (/usr/lib/node_modules/swagger-validator/node_modules/request/index.js:55:10)
    at /usr/lib/node_modules/swagger-validator/node_modules/request/index.js:101:12
```

**Comment by cbkelley** [comment]
I don't know if I'll get around to local file support.  The configuration for multiple file swagger documents feels like it could get really gnarly.  I'll take a stab at it and see what I can come up with.

**Comment by archanamahajan** [comment]
I also got the above issue when dealing with non complaint swagger API's.
Below is the link, where I have tried to resolve the issue. There is little change in index.js file.
https://github.com/archanamahajan/swaggerValidator.
Thanks.
